### ISSUE TITLE
Ratings of each app is fetched each time user opens app's window

### ISSUE THREAD

**Issue by farooqkz** [jkelol111/webstore#10]
**Describe the bug**
Each time user clicks on apps details, ratings information for the selected app is obtained from the server.
This puts unnecessary additional load on the rating server.

**To Reproduce**
I think it is too obious

**Expected behavior**
Caching

**Desktop (please complete the following information):**
Does not matter

**Comment by jkelol111** [comment]
I don't think this is an issue per se, as it's a way of refreshing the ratings list, as there is no endpoint to retrieve all ratings for all apps on SRS yet.

**Comment by farooqkz** [comment]
I think you got me wrong...
The problem is that there is no caching at all. Not even for a short time. If user opens an app's window then close it and open it immediately the ratings will be fetched twice. I think that's not what you want.

**Comment by jkelol111** [comment]
I don't think it is a big issue, as the ratings could change anytime in between even for a short period of time. If the SRS API gets an all app ratings endpoint in the future, I might work on this. For now, I think it is a good enough compromise.
