### ISSUE TITLE
Tags jump around

### ISSUE THREAD

**Issue by Simon-Laux** [jkelol111/webstore#4]
when enabling and disabling, I don't like that because my eyes need to re-scan the screen to find the tags again.
![Peek 2020-06-10 13-50](https://user-images.githubusercontent.com/18725968/84264422-739a8b80-ab21-11ea-81f9-80062d8bc414.gif)
I suggest to just change the color and don't move them around.

**Comment by jkelol111** [comment]
A new tab based system is in the making to replace tags.

**Comment by jkelol111** [comment]
Latest commits have fixed this issue by replacing tags with tabs.
