### ISSUE TITLE
Donate button does not work

### ISSUE THREAD

**Issue by farooqkz** [jkelol111/webstore#9]
**Describe the bug**
Donate button does not work

**To Reproduce**
1. Open the store
2. Wait till it loads data
3. Select an app(I have tried ADBRoot and Talking bot)
4. Press the yellow "Donate" button
5. Nothing happens

**Expected behavior**
Should I really tell you what is the expected behavior?!

**Desktop (please complete the following information):**
 - OS: GNU+Linux(Ubuntu 20.04 LTS x86_64)
 - Browser: Firefox
 - Version: 82.0.2

**Additional context**
In the console, I see this error when pressing the button:
Uncaught ReferenceError: e is not defined
onclick https://store.bananahackers.net/assets/js/index/controller.js:1

**Comment by jkelol111** [comment]
Should be fixed now.

**Comment by farooqkz** [comment]
Confirmed
